/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tbnrkrqhagfftlkmakws"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibnJrcnFoYWdmZnRsa21ha3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0Mzk0MDAsImV4cCI6MjA3NzAxNTQwMH0.-7EH-aeICpNlaR4zxfpp5bPw1iw-mr-3xxb45RnexYc"